language: ruby
rvm:
- 2.4
notifications:
  slack:
    secure: gljuOHCotdhsOWzk1vrQZE2IfExVzgX57LAMzXkwBgUozgDppcNacp7kMoNdxtnCJqcvPDLDpyc/F8wlvUFjJTMHcKqd4sQIGMuIt8Dgs0I+hPsUtVNVVk5LAvbNV71Q8bnnN5Yw/fSoWBAQQLlB8Yf8d3nATvCrsEYmTzNfE9A+hyyGxyv8qjrvcGBpNA4Ey1QKefUkIuT8dDd8Qu3zFntt3DELzfcwKSiC072xkaioPpNakMhoeJaLw4oMopq6YRynu6bNTrug9JchN8MH7yDvbXrS1hscYkfZIloFFivlAvDL6WglZCdJRaGf2EBn3cuI5J4wZfEEtQpxNRX+bpINzdHnstpJKpEd59Z+NSPm85jSDpB4QD+lEyqpMyg7zairCsNnzL/4u55ydjiLmbhgPh82gvzFJ4gbHHWGD8nxZltDJQ7kS9cfv4Ph6l36hyZblDx9qD8JVN+NfSpScQGD0YJ5VOENwqWCSozswZZ2f3bA91XnoBlUdtxb3TjNC+vPsz9n+Pt+TDAIy9Ywt4qL1tAaftsux4oIP+LX1lHptnmqabuMExu46QV9p5uClMGfrSLZB/beuLZ3sSd+ePryIY3wTfMYFRxcK35W3u0s/Y26l7m0BXNzK+i/Fd+F6tvB7ZpvlDsG+8keSZbEcEIgD9GCFrsOA2SumKfwfMs=
